"""Actual bridge implementation with fake CEF/MC, fake transport and synthetic identities only."""
from pathlib import Path
import sys,importlib.util,subprocess,tempfile,json
root=Path(__file__).resolve().parents[2];out=root/'build/friends-tests';out.mkdir(parents=True,exist_ok=True)
spec=importlib.util.spec_from_file_location('build',root/'build.py');build=importlib.util.module_from_spec(spec);spec.loader.exec_module(build)
javac,java=build.java_tools(Path(sys.argv[1]) if len(sys.argv)>1 else None);deps=Path(sys.argv[2]) if len(sys.argv)>2 else root/'build/friends-test-dependencies.jar'
files={
'net/muxigame/core/client/TerminalPassportApi.java':r'''package net.muxigame.core.client;public final class TerminalPassportApi {public static int requests;public static String value="{\"ticket\":\""+"A".repeat(43)+"\",\"verifier\":\""+"B".repeat(43)+"\",\"requestId\":\"11111111-1111-4111-8111-111111111111\"}";public static Runnable beforeReply=()->{};public static void request(java.util.function.Consumer<String> cb){requests++;beforeReply.run();cb.accept(value);}}''',
'net/muxigame/minigames/client/TerminalGamesApi.java':'''package net.muxigame.minigames.client;public class TerminalGamesApi {public static com.google.gson.JsonObject raw;public static int sent;public static String snapshotJson(){return raw.toString();}public static void request(){}public static String submit(String g,String a,String v){sent++;return \"{\\\"ok\\\":true,\\\"request\\\":\\\"22222222-2222-4222-8222-222222222222\\\"}\";}}''',
'org/cef/browser/CefBrowser.java':'''package org.cef.browser;public class CefBrowser {public String url;public int identifier=7;public CefFrame main;public String getURL(){return url;}}''',
'org/cef/browser/CefFrame.java':'''package org.cef.browser;public class CefFrame {public String url;public boolean valid=true,main=true;public String getURL(){return url;}}''',
'org/cef/callback/CefQueryCallback.java':'''package org.cef.callback;public interface CefQueryCallback {void success(String s);void failure(int code,String s);}''',
'net/minecraft/client/gui/screens/ChatScreen.java':'''package net.minecraft.client.gui.screens;public class ChatScreen {public final String prefill;public ChatScreen(String value){prefill=value;}}''',
'net/minecraft/client/multiplayer/PlayerInfo.java':'''package net.minecraft.client.multiplayer;public class PlayerInfo {public com.mojang.authlib.GameProfile profile;public PlayerInfo(com.mojang.authlib.GameProfile p){profile=p;}public com.mojang.authlib.GameProfile getProfile(){return profile;}}''',
'net/minecraft/client/multiplayer/ClientPacketListener.java':'''package net.minecraft.client.multiplayer;public class ClientPacketListener {public com.mojang.authlib.GameProfile local=new com.mojang.authlib.GameProfile(net.muxigame.terminal.client.TerminalFriendsPolicy.playerUuid("100001"),"100001");public java.util.Map<java.util.UUID,PlayerInfo> players=new java.util.HashMap<>();public com.mojang.brigadier.CommandDispatcher<Object> commands=new com.mojang.brigadier.CommandDispatcher<>();public int sent;public com.mojang.authlib.GameProfile getLocalGameProfile(){return local;}public PlayerInfo getPlayerInfo(java.util.UUID uid){return players.get(uid);}public com.mojang.brigadier.CommandDispatcher<Object> getCommands(){return commands;}public void sendChat(String text){sent++;}public void sendCommand(String text){sent++;}}''',
'net/minecraft/client/Minecraft.java':'''package net.minecraft.client;public class Minecraft {public static final Minecraft INSTANCE=new Minecraft();public Object screen=new net.muxigame.terminal.client.TerminalScreen(),level=new Object();public Player player=new Player();public net.minecraft.client.multiplayer.ClientPacketListener connection=new net.minecraft.client.multiplayer.ClientPacketListener();public boolean focused=true;public static Minecraft getInstance(){return INSTANCE;}public boolean isWindowActive(){return focused;}public net.minecraft.client.multiplayer.ClientPacketListener getConnection(){return connection;}public void execute(Runnable r){r.run();}public void setScreen(Object screen){this.screen=screen;}public static class Player {public boolean alive=true;public boolean isAlive(){return alive;}}}''',
'net/muxigame/terminal/client/TerminalScreen.java':'''package net.muxigame.terminal.client;public class TerminalScreen {}''',
'net/muxigame/terminal/client/TerminalBrowserSession.java':'''package net.muxigame.terminal.client;import org.cef.browser.*;public class TerminalBrowserSession {public static String HOME_URL="mod://muxi_terminal/terminal/index.html";public enum Kind{HOME,BUILTIN,WEB,ACCOUNT}public record State(Kind kind){}public static Kind kind=Kind.BUILTIN;public static long gen=1;public static CefBrowser browser=new CefBrowser();public static CefBrowser content(){return browser;}public static long generation(){return gen;}public static State state(){return new State(kind);}public static boolean trusted(CefBrowser b,CefFrame f){return b==browser && f!=null && f==b.main && f.valid && f.main && b.url.equals(f.url);}}''',
'net/muxigame/terminal/client/FriendsBridgeTest.java':r'''package net.muxigame.terminal.client;
import com.google.gson.*;import org.cef.browser.*;import org.cef.callback.*;import net.minecraft.client.Minecraft;import java.util.*;import java.util.concurrent.*;import java.net.http.*;import net.minecraft.client.multiplayer.PlayerInfo;import com.mojang.authlib.GameProfile;import net.minecraft.client.gui.screens.ChatScreen;
public class FriendsBridgeTest {
static int checks;static void check(boolean b,String text){checks++;if(!b)throw new AssertionError(text);}static class Reply implements CefQueryCallback{String value;int code;CountDownLatch done=new CountDownLatch(1);public void success(String s){value=s;done.countDown();}public void failure(int c,String s){code=c;value=s;done.countDown();}void waitReply()throws Exception{check(done.await(3,TimeUnit.SECONDS),"callback completes");}}
static Reply call(CefBrowser b,CefFrame f,String text){var r=new Reply();check(TerminalFriendsBridge.dispatch(b,f,text,r),"friends command recognized");return r;}
static void idle()throws Exception{var field=TerminalFriendsBridge.class.getDeclaredField("BUSY");field.setAccessible(true);var flag=(java.util.concurrent.atomic.AtomicBoolean)field.get(null);long until=System.nanoTime()+3_000_000_000L;while(flag.get()&&System.nanoTime()<until)Thread.sleep(5);check(!flag.get(),"bounded worker released");}
public static void main(String[] args)throws Exception{
var mc=Minecraft.getInstance();Object screen=mc.screen;var browser=TerminalBrowserSession.browser;var frame=new CefFrame();browser.main=frame;browser.url=TerminalBrowserSession.HOME_URL+"#/friends";frame.url=browser.url;
var profile=new GameProfile(TerminalFriendsPolicy.playerUuid("100002"),"100002");mc.connection.players.put(profile.getId(),new PlayerInfo(profile));mc.connection.commands.register(com.mojang.brigadier.builder.LiteralArgumentBuilder.literal("msg"));
var nativeRoot=new JsonObject();nativeRoot.addProperty("protocol",2);nativeRoot.addProperty("actionSupported",true);nativeRoot.add("games",new JsonArray());var nativeSocial=new JsonObject();nativeSocial.addProperty("version",1);nativeSocial.addProperty("enabled",true);nativeSocial.addProperty("authenticated",true);var nativePeers=new JsonArray();var np=new JsonObject();np.addProperty("uid","100002");np.addProperty("uuid",profile.getId().toString());np.addProperty("gameName","100002");np.addProperty("displayName","test");nativePeers.add(np);nativeSocial.add("onlinePlayers",nativePeers);nativeSocial.add("invitations",new JsonArray());nativeRoot.add("social",nativeSocial);net.muxigame.minigames.client.TerminalGamesApi.raw=nativeRoot;
String nativePayload=TerminalFriendsTransport.passport();
check(nativePayload.equals(net.muxigame.core.client.TerminalPassportApi.value),"actual existing passport API called from native transport");
TerminalFriendsTransport.passport();check(net.muxigame.core.client.TerminalPassportApi.requests==2,"each operation rechecks current launcher identity, no session cache");
var savedConnection=mc.connection;net.muxigame.core.client.TerminalPassportApi.beforeReply=()->mc.connection=new net.minecraft.client.multiplayer.ClientPacketListener();
try{TerminalFriendsTransport.passport();throw new AssertionError("connection change accepted");}catch(TerminalFriendsTransport.Failure error){check(error.code==409,"connection change cannot exchange an old passport");}
mc.connection=savedConnection;net.muxigame.core.client.TerminalPassportApi.beforeReply=()->{};
var savedNative=net.muxigame.core.client.TerminalPassportApi.value;net.muxigame.core.client.TerminalPassportApi.value="";
try{TerminalFriendsTransport.originalAccess(TerminalFriendsTransport.passport());throw new AssertionError("logged out launcher accepted");}catch(TerminalFriendsTransport.Failure error){check(error.code==401,"logged out launcher fails closed without interactive login");}
net.muxigame.core.client.TerminalPassportApi.value=savedNative;
var calls=new CopyOnWriteArrayList<HttpRequest>();var cookieReads=new java.util.concurrent.atomic.AtomicInteger();var snapshot=FriendsPolicyTest.data();var latch=new CountDownLatch[]{null,null};
var transport=new TerminalFriendsTransport(()->{cookieReads.incrementAndGet();return "synthetic_cookie_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";},r->{calls.add(r);if(latch[0]!=null){latch[0].countDown();latch[1].await(3,TimeUnit.SECONDS);}if(r.method().equals("GET"))return new TerminalFriendsTransport.Response(200,snapshot.toString());return new TerminalFriendsTransport.Response(200,"{\"version\":1,\"request\":\""+r.headers().firstValue("Idempotency-Key").orElseThrow()+"\",\"status\":\"ok\",\"ok\":true,\"changed\":true}");});
var transportField=TerminalFriendsBridge.class.getDeclaredField("TRANSPORT");transportField.setAccessible(true);transportField.set(null,transport);
for(var kind:new TerminalBrowserSession.Kind[]{TerminalBrowserSession.Kind.HOME,TerminalBrowserSession.Kind.WEB,TerminalBrowserSession.Kind.ACCOUNT}){TerminalBrowserSession.kind=kind;check(call(browser,frame,"friends.snapshot").code==403,"non builtin denied");}TerminalBrowserSession.kind=TerminalBrowserSession.Kind.BUILTIN;
var imposter=new CefBrowser();imposter.url=browser.url;imposter.main=frame;check(call(imposter,frame,"friends.snapshot").code==403,"same numeric browser ID cannot gain capability");
var iframe=new CefFrame();iframe.url=browser.url;check(call(browser,iframe,"friends.snapshot").code==403,"different actual frame denied");frame.main=false;check(call(browser,frame,"friends.snapshot").code==403,"iframe denied");frame.main=true;
String route=browser.url;browser.url=TerminalBrowserSession.HOME_URL+"#/album";frame.url=browser.url;check(call(browser,frame,"friends.snapshot").code==403,"other builtin denied");browser.url=route;frame.url=route;
check(cookieReads.get()==0 && calls.isEmpty(),"denial reads no cookie and sends no HTTP");
var loaded=call(browser,frame,"friends.snapshot");loaded.waitReply();idle();check(loaded.code==0 && loaded.value.contains("messageAvailable\":true") && !loaded.value.contains("synthetic_cookie"),"safe snapshot and actual command capability, no session in renderer");
var chat=call(browser,frame,"friends.message:100002");check(chat.code==0 && mc.screen instanceof ChatScreen && ((ChatScreen)mc.screen).prefill.equals("/msg 100002 "),"original ChatScreen prefill");check(mc.connection.sent==0,"no message or command sent");mc.screen=screen;
mc.connection.players.clear();check(call(browser,frame,"friends.message:100002").code==400,"disconnected recipient denied");mc.connection.players.put(profile.getId(),new PlayerInfo(profile));
String action="friends.action:{\"op\":\"request\",\"uid\":\"100003\",\"request\":\"11111111-1111-4111-8111-111111111111\"}";
int start=calls.size();var changed=call(browser,frame,action);changed.waitReply();idle();check(changed.code==0 && calls.size()==start+2 && calls.get(start).method().equals("GET") && calls.get(start+1).method().equals("PUT"),"each write preflights authenticated actor with same cookie");
snapshot.addProperty("selfUid","100009");start=calls.size();var mismatch=call(browser,frame,action);mismatch.waitReply();idle();check(mismatch.code==400 && calls.size()==start+1,"wrong website account cannot mutate");snapshot.addProperty("selfUid","100001");
start=calls.size();check(call(browser,frame,action.replace("request\",","request\",\"actor\":\"100009\"," )).code==400,"browser actor injection rejected");check(calls.size()==start,"malformed command cannot invoke HTTP");
for(int scenario=0;scenario<4;scenario++){
latch[0]=new CountDownLatch(1);latch[1]=new CountDownLatch(1);start=calls.size();var pending=call(browser,frame,action);check(latch[0].await(2,TimeUnit.SECONDS),"synthetic preflight paused");
Object oldScreen=mc.screen;var oldConnection=mc.connection;long oldGeneration=TerminalBrowserSession.gen;if(scenario==0)frame.url="https://outside.example/";if(scenario==1)mc.screen=null;if(scenario==2)mc.connection=new net.minecraft.client.multiplayer.ClientPacketListener();if(scenario==3)TerminalBrowserSession.gen++;
latch[1].countDown();idle();check(pending.code==409 && "Terminal context changed".equals(pending.value) && calls.size()==start+1,"stale frame/screen/connection/generation settles failure without writing");frame.url=route;mc.screen=oldScreen;mc.connection=oldConnection;TerminalBrowserSession.gen=oldGeneration;latch[0]=latch[1]=null;}
browser.url=TerminalBrowserSession.HOME_URL+"#/games";frame.url=browser.url;check(call(browser,frame,action).code==403,"game page cannot mutate friendship");var peers=call(browser,frame,"friends.invite-peers");peers.waitReply();idle();var projection=JsonParser.parseString(peers.value).getAsJsonObject();check(!projection.has("incoming")&&!projection.has("blocked")&&projection.getAsJsonObject("runtime").get("enabled").getAsBoolean(),"game picker receives only scoped roster and native invitation capability");

var nativeGames=nativeRoot.getAsJsonArray("games");var ng=new JsonObject();ng.addProperty("id","zombie-challenge");var ns=new JsonObject();var nr=new JsonArray();var room=new JsonObject();String session="33333333-3333-4333-8333-333333333333";room.addProperty("session",session);room.addProperty("host",mc.connection.local.getId().toString());room.addProperty("socialManaged",true);room.addProperty("mine",true);room.addProperty("phase","LOBBY");nr.add(room);ns.add("rooms",nr);ng.add("state",ns);nativeGames.add(ng);
var current=TerminalFriendsInvitesBridge.snapshot();check(current.getAsJsonArray("rooms").get(0).getAsJsonObject().get("inviteable").getAsBoolean(),"native full-session host waiting room available");
String issue="{\"op\":\"issue\",\"game\":\"zombie-challenge\",\"source\":\"online\",\"room\":\""+session+"\",\"uid\":\"100002\"}";var invite=TerminalFriendsInvitesPolicy.action(issue,current);check(invite.action().equals("inviteOnline")&&invite.value().equals(session+"|"+profile.getId()),"UID maps to actual native UUID without acting UID");
for(String invalid:new String[]{issue.replace(session,"33333333"),issue.replace("100002","100009"),issue.replace("online","unknown"),issue.replace("\"uid\":","\"actor\":\"100001\",\"uid\":")}){boolean denied=false;try{TerminalFriendsInvitesPolicy.action(invalid,current);}catch(RuntimeException e){denied=true;}check(denied,"invalid room/target/source/actor denied");}
room.addProperty("socialManaged",false);check(TerminalFriendsInvitesBridge.snapshot().getAsJsonArray("rooms").isEmpty(),"mixed old module cannot enable room invite");room.addProperty("socialManaged",true);room.addProperty("phase","RUNNING");check(!TerminalFriendsInvitesBridge.snapshot().getAsJsonArray("rooms").get(0).getAsJsonObject().get("inviteable").getAsBoolean(),"running room cannot invite");room.addProperty("phase","LOBBY");
var ticket=new JsonObject();ticket.addProperty("invitation","44444444-4444-4444-8444-444444444444");ticket.addProperty("room",session);ticket.addProperty("game","zombie-challenge");ticket.addProperty("host",profile.getId().toString());ticket.addProperty("target",mc.connection.local.getId().toString());ticket.addProperty("source","online");ticket.addProperty("status","PENDING");ticket.addProperty("expiresInSeconds",300);nativeSocial.getAsJsonArray("invitations").add(ticket);
String accept="{\"op\":\"accept\",\"game\":\"zombie-challenge\",\"invitation\":\"44444444-4444-4444-8444-444444444444\"}";check(TerminalFriendsInvitesPolicy.action(accept,TerminalFriendsInvitesBridge.snapshot()).action().equals("inviteAccept"),"recipient can accept exact ticket");boolean denied=false;try{TerminalFriendsInvitesPolicy.action(accept.replace("accept","cancel"),TerminalFriendsInvitesBridge.snapshot());}catch(RuntimeException e){denied=true;}check(denied,"recipient cannot cancel host ticket");ticket.addProperty("expiresInSeconds",0);denied=false;try{TerminalFriendsInvitesPolicy.action(accept,TerminalFriendsInvitesBridge.snapshot());}catch(RuntimeException e){denied=true;}check(denied,"expired ticket cannot submit");ticket.addProperty("expiresInSeconds",300);
var ack=call(browser,frame,"friends.invites.action:"+issue);check(ack.code==0&&ack.value.contains("request"),"native submission returns acknowledgement only");check(call(browser,frame,"friends.invites.action:"+issue).code==400,"second pending mutation blocked");var operation=new JsonObject();operation.addProperty("request","22222222-2222-4222-8222-222222222222");operation.addProperty("status","pending");nativeRoot.add("operation",operation);check(call(browser,frame,"friends.invites.action:"+issue).code==400,"pending receipt cannot release gate");operation.addProperty("status","completed");check(call(browser,frame,"friends.invites.action:"+issue).code==0,"final matching receipt releases gate");
var generic=new Reply();TerminalGameAppsBridge.dispatch(browser,frame,"games.action:{\"game\":\"zombie-challenge\",\"action\":\"inviteOnline\",\"value\":\""+session+"|"+profile.getId()+"\"}",generic);check(generic.code==400,"generic bridge cannot bypass scoped invitation validation");
int packets=net.muxigame.minigames.client.TerminalGamesApi.sent;frame.url="https://outside.example";check(call(browser,frame,"friends.invites.action:"+issue).code==403,"external frame cannot submit invitation");frame.url=browser.url;check(packets==net.muxigame.minigames.client.TerminalGamesApi.sent,"denied frame emits no packet");nativeSocial.addProperty("enabled",false);check(!TerminalFriendsInvitesBridge.snapshot().get("enabled").getAsBoolean(),"disabled server fails closed");nativeSocial.addProperty("enabled",true);

check(TerminalFriendsInvitesPolicy.GAMES.equals(Set.of("zombie-challenge","outbreak","flight","tower_defense")),"invitation game allowlist remains exact");
ng.addProperty("id","flight");room.addProperty("phase","WAITING");room.addProperty("lobbyWaiting",true);ticket.addProperty("game","flight");
String flightIssue=issue.replace("zombie-challenge","flight"),flightAccept=accept.replace("zombie-challenge","flight");
var flightSnapshot=TerminalFriendsInvitesBridge.snapshot();check(flightSnapshot.getAsJsonArray("rooms").get(0).getAsJsonObject().get("inviteable").getAsBoolean(),"actual SDK flight social-managed waiting host is projected");
var flightAction=TerminalFriendsInvitesPolicy.action(flightIssue,flightSnapshot);check(flightAction.game().equals("flight")&&flightAction.action().equals("inviteOnline")&&flightAction.value().equals(session+"|"+profile.getId()),"flight uses existing room and verified online peer packet contract");
check(TerminalFriendsInvitesPolicy.action(flightIssue.replace("online","friends"),flightSnapshot).action().equals("inviteFriends"),"flight uses existing friends invitation authority");
check(TerminalFriendsInvitesPolicy.action(flightAccept,flightSnapshot).action().equals("inviteAccept"),"flight recipient accepts exact pending ticket");
for(String invalid:new String[]{flightIssue.replace("flight","arbitrary-mode"),flightIssue.replace("100002","100009"),flightIssue.replace(session,"55555555-5555-4555-8555-555555555555"),flightIssue.replace("\"uid\":","\"actor\":\"100001\",\"uid\":"),flightAccept.replace("accept","cancel")}){boolean blocked=false;try{TerminalFriendsInvitesPolicy.action(invalid,flightSnapshot);}catch(RuntimeException e){blocked=true;}check(blocked,"flight rejects unknown mode, absent peer, wrong room, actor injection or unauthorized ticket role");}
room.remove("socialManaged");check(TerminalFriendsInvitesBridge.snapshot().getAsJsonArray("rooms").isEmpty(),"flight without server socialManaged remains unavailable");room.addProperty("socialManaged",true);
room.addProperty("lobbyWaiting",false);check(!TerminalFriendsInvitesBridge.snapshot().getAsJsonArray("rooms").get(0).getAsJsonObject().get("inviteable").getAsBoolean(),"flight requires server lobby waiting qualification");room.addProperty("lobbyWaiting",true);
room.addProperty("phase","RUNNING");check(!TerminalFriendsInvitesBridge.snapshot().getAsJsonArray("rooms").get(0).getAsJsonObject().get("inviteable").getAsBoolean(),"running flight cannot invite");room.addProperty("phase","WAITING");
room.addProperty("mine",false);check(!TerminalFriendsInvitesBridge.snapshot().getAsJsonArray("rooms").get(0).getAsJsonObject().get("inviteable").getAsBoolean(),"flight non-owner room cannot invite");room.addProperty("mine",true);
room.addProperty("host",profile.getId().toString());check(!TerminalFriendsInvitesBridge.snapshot().getAsJsonArray("rooms").get(0).getAsJsonObject().get("inviteable").getAsBoolean(),"flight claimed mine cannot override actual host UUID");room.addProperty("host",mc.connection.local.getId().toString());
ticket.addProperty("expiresInSeconds",0);boolean expiredFlight=false;try{TerminalFriendsInvitesPolicy.action(flightAccept,TerminalFriendsInvitesBridge.snapshot());}catch(RuntimeException e){expiredFlight=true;}check(expiredFlight,"expired flight invitation rejected");ticket.addProperty("expiresInSeconds",300);
nativeSocial.addProperty("authenticated",false);boolean unauthenticatedFlight=false;try{TerminalFriendsInvitesPolicy.action(flightIssue,TerminalFriendsInvitesBridge.snapshot());}catch(RuntimeException e){unauthenticatedFlight=true;}check(unauthenticatedFlight,"flight unauthenticated SDK denied");nativeSocial.addProperty("authenticated",true);
ng.addProperty("id","tower_defense");ticket.addProperty("game","tower_defense");
String towerIssue=issue.replace("zombie-challenge","tower_defense"),towerAccept=accept.replace("zombie-challenge","tower_defense");
var towerSnapshot=TerminalFriendsInvitesBridge.snapshot();check(towerSnapshot.getAsJsonArray("rooms").get(0).getAsJsonObject().get("inviteable").getAsBoolean(),"tower waiting social host is projected");
check(TerminalFriendsInvitesPolicy.action(towerIssue,towerSnapshot).value().equals(session+"|"+profile.getId()),"tower issue uses exact session and verified UUID");
check(TerminalFriendsInvitesPolicy.action(towerIssue.replace("online","friends"),towerSnapshot).action().equals("inviteFriends"),"tower friends source retains authorization contract");
check(TerminalFriendsInvitesPolicy.action(towerAccept,towerSnapshot).action().equals("inviteAccept"),"tower recipient accepts exact pending ticket");
for(String invalid:new String[]{towerIssue.replace("tower_defense","arbitrary-mode"),towerIssue.replace("100002","100009"),towerIssue.replace(session,"55555555-5555-4555-8555-555555555555"),towerIssue.replace("\"uid\":","\"actor\":\"100001\",\"uid\":"),towerAccept.replace("accept","cancel")}){boolean blocked=false;try{TerminalFriendsInvitesPolicy.action(invalid,towerSnapshot);}catch(RuntimeException e){blocked=true;}check(blocked,"tower unknown game, absent peer, wrong room, actor injection and ticket role remain blocked");}
room.addProperty("socialManaged",false);check(TerminalFriendsInvitesBridge.snapshot().getAsJsonArray("rooms").isEmpty(),"legacy tower room cannot claim trusted invitations");room.addProperty("socialManaged",true);
for(String field:List.of("mine","lobbyWaiting")){room.addProperty(field,false);check(!TerminalFriendsInvitesBridge.snapshot().getAsJsonArray("rooms").get(0).getAsJsonObject().get("inviteable").getAsBoolean(),"tower requires "+field);room.addProperty(field,true);}
room.addProperty("host",profile.getId().toString());check(!TerminalFriendsInvitesBridge.snapshot().getAsJsonArray("rooms").get(0).getAsJsonObject().get("inviteable").getAsBoolean(),"tower actual host UUID required");room.addProperty("host",mc.connection.local.getId().toString());
room.addProperty("phase","RUNNING");check(!TerminalFriendsInvitesBridge.snapshot().getAsJsonArray("rooms").get(0).getAsJsonObject().get("inviteable").getAsBoolean(),"tower running invite denied");room.addProperty("phase","WAITING");
ticket.addProperty("expiresInSeconds",0);boolean expiredTower=false;try{TerminalFriendsInvitesPolicy.action(towerAccept,TerminalFriendsInvitesBridge.snapshot());}catch(RuntimeException e){expiredTower=true;}check(expiredTower,"tower expired ticket denied");ticket.addProperty("expiresInSeconds",300);
nativeSocial.addProperty("authenticated",false);boolean anonymousTower=false;try{TerminalFriendsInvitesPolicy.action(towerIssue,TerminalFriendsInvitesBridge.snapshot());}catch(RuntimeException e){anonymousTower=true;}check(anonymousTower,"tower unauthenticated actor denied");nativeSocial.addProperty("authenticated",true);
check(mc.connection.sent==0,"all scenarios remain prefill only");System.out.println("{\"success\":true,\"checks\":"+checks+",\"scope\":\"production bridge code with simulated CEF/MC and fake HTTP, no real cookie/network/player\"}");
}}
'''
}
with tempfile.TemporaryDirectory(dir=out) as tmp:
    tmp=Path(tmp);sources=[]
    for name,source in files.items():
        path=tmp/'stubs'/name;path.parent.mkdir(parents=True,exist_ok=True);path.write_text(source,encoding='utf-8');sources.append(path)
    sources += [root/'src/main/java/net/muxigame/terminal/client'/name for name in ['TerminalFriendsBridge.java','TerminalFriendsPolicy.java','TerminalFriendsTransport.java','TerminalFriendsInvitesPolicy.java','TerminalFriendsInvitesBridge.java','TerminalGameActionGate.java','TerminalGameAppsBridge.java']]+[root/'tests/friends/FriendsPolicyTest.java']
    build.compile_java(javac,sources,tmp/'classes',str(deps),tmp/'args')
    result=subprocess.run([str(java),'-cp',str(tmp/'classes')+';'+str(deps),'net.muxigame.terminal.client.FriendsBridgeTest'],capture_output=True)
    print(result.stdout.decode('utf-8','replace'));print(result.stderr.decode('utf-8','replace'));result.check_returncode()
    (out/'bridge-result.json').write_text(json.dumps(json.loads(result.stdout),indent=2)+'\n',encoding='utf-8')
