const assert=require('node:assert/strict');
const M=require('../src/main/resources/assets/muxi_terminal/html/terminal/apps/minigames/model.js');
let passed=0;function check(name,fn){fn();passed++;}
const fields={fields:[{id:'map',selected:'research_lab',options:[{value:'research_lab'},{value:'mysterious_camp'}]},{id:'difficulty',selected:'NORMAL',options:[{value:'NORMAL'},{value:'EXTREME'}]}]};
check('map and difficulty form drafts reach the existing validated create action',()=>assert.equal(M.actionValue('zombie-challenge',{value:'{map}|{difficulty}'},fields,{'zombie-challenge:map':'mysterious_camp','zombie-challenge:difficulty':'EXTREME'}),'mysterious_camp|EXTREME'));
check('polling keeps a valid draft',()=>assert.equal(M.values('zombie-challenge',fields,{'zombie-challenge:map':'mysterious_camp'}).map,'mysterious_camp'));
check('removed options reject stale selection',()=>assert.equal(M.values('zombie-challenge',fields,{'zombie-challenge:map':'removed'}).map,'research_lab'));
check('game drafts stay separate',()=>assert.equal(M.values('zombie-challenge',fields,{'outbreak:map':'mysterious_camp'}).map,'research_lab'));
check('Outbreak creation sends only declared fields',()=>assert.deepEqual(JSON.parse(M.actionValue('outbreak',{jsonFields:true,fields:'map,difficulty'},fields,{})),{map:'research_lab',difficulty:'NORMAL'}));
check('incomplete form cannot submit',()=>assert.throws(()=>M.actionValue('g',{value:'{missing}'},fields,{})));
check('quote and revision stay server-authored',()=>assert.equal(M.actionValue('g',{value:'medkit:7:4'},fields,{}),'medkit:7:4'));
check('ban disables a purchase',()=>assert.equal(M.blocked({allowed:false},'g',{enabled:true}),true));
check('ban keeps safe return available',()=>assert.equal(M.blocked({allowed:false},'g',{enabled:true,safe:true}),false));
check('cross-game membership blocks new actions',()=>assert.equal(M.blocked({allowed:true,activeGame:'other'},'g',{enabled:true}),true));
check('server eligibility cannot be enabled by a client balance',()=>assert.equal(M.blocked({allowed:true},'g',{enabled:false}),true));
check('platform amount retains integer precision',()=>assert.equal(M.platformText({available:true,points:'9223372036854775807'}),'9223372036854775807'));
check('unknown platform amount does not become zero',()=>assert.equal(M.platformText({available:false}),'尚未同步'));
check('labels escape injected HTML',()=>assert.equal(M.esc('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;'));
check('context persists one APP internal shop page',()=>assert.deepEqual(M.cleanContext({game:'zombie-challenge',page:'shop',drafts:{'zombie-challenge:map':'mysterious_camp'}}),{game:'zombie-challenge',page:'shop',drafts:{'zombie-challenge:map':'mysterious_camp'}}));
check('context drops unsafe navigation fields',()=>assert.deepEqual(M.cleanContext({game:'https://evil',page:'account',uid:10000,drafts:{'bad/path':'x'}}),{game:'',page:'lobby',drafts:{}}));
check('mode-map filtering does not depend on server field order',()=>{
  const owner={fields:[{id:'map',selected:'campaign-only',options:[{value:'campaign-only',modes:['CAMPAIGN']},{value:'survival-only',modes:['SURVIVAL']}]},{id:'mode',selected:'CAMPAIGN',options:[{value:'CAMPAIGN'},{value:'SURVIVAL'}]}]};
  assert.deepEqual(M.values('outbreak',owner,{'outbreak:mode':'SURVIVAL','outbreak:map':'campaign-only'}),{mode:'SURVIVAL',map:'survival-only'});
});
check('active room never exposes invitations even if a stale waiting flag remains',()=>assert.equal(M.waiting({phase:'ACTIVE',lobbyWaiting:true}),false));
check('native waiting phases expose invitations',()=>assert.equal(M.waiting({phase:'WAITING',lobbyWaiting:true}),true));
check('countdown cannot mutate waiting settings',()=>assert.equal(M.waiting({phase:'COUNTDOWN',lobbyWaiting:true}),false));
check('nickname default has bounded UTF16 length',()=>{assert.equal(M.defaultName('Tester'),'Tester的房间');assert.equal(M.defaultName('😀'.repeat(20)).length,23);});
check('names cannot smuggle formatting or exceed packet name limit',()=>{for(const value of ['', 'a'.repeat(25),'bad\nname','bad§name','bad\u200Bname'])assert.throws(()=>M.roomName(value));});
console.log(`Minigames terminal model: ${passed} meaningful boundary checks passed`);

const session='11111111-1111-4111-8111-111111111111',seat='22222222-2222-4222-8222-222222222222';
const aiSnapshot={protocol:2,roomAiVersion:1,allowed:true,self:{uuid:'host'},activeGame:'outbreak'};
const aiGame={id:'outbreak',roomCapabilities:{aiTeammates:{supported:true}}};
const aiRoom={session,host:'host',phase:'WAITING',count:1,capacity:4,ai:{supported:true,editable:true,locked:false,revision:'0'},roster:[]};
check('host waiting AI add packet contains session and CAS only',()=>assert.deepEqual(JSON.parse(M.aiPacket(aiSnapshot,aiGame,aiRoom,'aiAdd')),[session,'0']));
check('nonhost cannot add despite forged editable state',()=>assert.equal(M.aiControls(aiSnapshot,aiGame,{...aiRoom,host:'other'}).editable,false));
check('full human plus AI room disables add',()=>assert.throws(()=>M.aiPacket(aiSnapshot,aiGame,{...aiRoom,count:4},'aiAdd')));
check('native playing lock refuses UI seat changes',()=>assert.equal(M.aiControls(aiSnapshot,aiGame,{...aiRoom,ai:{...aiRoom.ai,editable:false,locked:true}}).editable,false));
check('unsupported game cannot expose manual AI even if declarations are forged',()=>{for(const id of ['flight','horse_racing','fixture'])assert.equal(M.aiControls({...aiSnapshot,activeGame:id},{...aiGame,id},aiRoom).supported,false);});
check('missing backend version or owner capability hides AI controls',()=>{assert.equal(M.aiControls({...aiSnapshot,roomAiVersion:undefined},aiGame,aiRoom).supported,false);assert.equal(M.aiControls(aiSnapshot,{...aiGame,roomCapabilities:{}},aiRoom).supported,false);});
check('invalid or exhausted revisions cannot mutate',()=>{for(const revision of ['00','-1','1e3','9223372036854775807',0])assert.equal(M.aiControls(aiSnapshot,aiGame,{...aiRoom,ai:{...aiRoom.ai,revision}}).editable,false);});
check('remove requires actual AI roster identity',()=>{assert.throws(()=>M.aiPacket(aiSnapshot,aiGame,aiRoom,'aiRemove',seat));const room={...aiRoom,roster:[{kind:'ai',aiId:seat}],ai:{...aiRoom.ai,revision:'1'}};assert.deepEqual(JSON.parse(M.aiPacket(aiSnapshot,aiGame,room,'aiRemove',seat)),[session,'1',seat]);});
check('AI ACK requires matching revision and actual new roster seat',()=>{const operation={ai:'aiAdd',session,nextAiRevision:'1',beforeAiIds:[]};assert.equal(M.aiConfirmed(aiRoom,operation),false);assert.equal(M.aiConfirmed({...aiRoom,ai:{...aiRoom.ai,revision:'1'}},operation),false);assert.equal(M.aiConfirmed({...aiRoom,ai:{...aiRoom.ai,revision:'1'},roster:[{kind:'ai',aiId:seat}]},operation),true);});
check('remove receipt requires actual seat disappearance in same room',()=>{const operation={ai:'aiRemove',session,nextAiRevision:'2',beforeAiIds:[seat],aiId:seat};const room={...aiRoom,ai:{...aiRoom.ai,revision:'2'}};assert.equal(M.aiConfirmed(room,operation),true);assert.equal(M.aiConfirmed({...room,roster:[{kind:'ai',aiId:seat}]},operation),false);assert.equal(M.aiConfirmed({...room,session:'other'},operation),false);});
console.log(`Minigames terminal model including AI: ${passed} meaningful boundary checks passed`);
